---
- hosts: all 
  gather_facts: False
  tasks:
  - name: check for missing hosts
    blocks:
    - name: limit
      set_fact:
        bb: '{{ groups.all }}'
        cc: '{{ ansible_limit.split(",") | difference(groups.all) }}'
    - name: check if host exist in inventory
      fail:
         msg: "Host: {{ cc | join(',') }} does not exist in inventory "
      ignore_errors: true
      when: cc not in bb  and cc | length > 0
    run_once: true
  - name: assert that output is a
    assert:
      that: output == 'a'
      msg: output does not equal a
    register: assert_register

  - name: assert that output is a
    assert:
      that: output == 'a'
      msg: output does not equal a
    register: assert_register
